feat: add Zola
netlify/framework-info pull request #326
Opened 2021-06-29 19:27 UTC by henrifrancois

Adds support for Zola

2021-06-30 09:28 UTC, erezrokah requested changes
Thanks @henrifrancois!

You should `require` the JSON file in:
https://github.com/netlify/framework-info/blob/4a28a9a9cbf64137a620f8dbe5b560e087e30f0e/src/frameworks/main.js#L29

Also how can we differentiate Zola from Hugo? See:
https://github.com/netlify/framework-info/blob/fb0416a39b7768e1103f3b01be9a272f17c37ce5/src/frameworks/hugo.json#L8

2021-06-30 17:07 UTC, henrifrancois commented
After reviewing it seems Zola _only_ uses a `config.toml` for its configuration options. I am unsure if that's a sufficient distinction between them both, however.

2021-06-30 17:19 UTC, erezrokah requested changes
Thanks for checking @henrifrancois.

I think this means that sometimes we'll detect both `hugo` and `zola` until we find a better way to do it (I believe we'll need to add support for pattern matching inside configuration files).

2021-06-30 17:19 UTC, erezrokah commented on package-lock.json
> +        "webpack": "^5.10.1",
Can we undo this? Seems unrelated to the PR

2021-07-05 11:24 UTC, erezrokah approved these changes

2021-07-05 11:25 UTC, merged

2021-07-05 11:25 UTC, erezrokah commented
Thanks @henrifrancois, I opened https://github.com/netlify/framework-info/issues/329 as a follow up