fix(sveltekit): specify better output location
netlify/framework-info pull request #380
Opened 2021-08-16 22:18 UTC by benmccann

I don't know why it says `static`. That's an input directory where static assets are located and we shouldn't put output there

2021-08-17 11:21 UTC, erezrokah requested changes
Hi @benmccann, can you point me to the relevant docs that show the location of the build directory?
I tried running a build locally and it builds to `.svelte-kit/build`, but I might have an older version.

Also, should we add `staticAssetsDirectory` with a value of `static`?
See  https://github.com/netlify/framework-info/blob/74f58312c75e6e8e89ebbfa3ec6d80419a2dc120/src/frameworks/create-react-app.json#L19

2021-08-17 16:52 UTC, benmccann commented
I've updated this PR to set `staticAssetsDirectory`

SvelteKit's `adapter-netlify` requires the build directory be set in `netlify.toml` and then reads that file to put the output in the specified location, so it can be any location. By default today [the docs](https://github.com/sveltejs/kit/tree/master/packages/adapter-netlify#installation) recommend:
```
[build]
  command = "npm run build"
  publish = "build/publish/"
  functions = "build/functions/"
```

However, SvelteKit is currently not really compatible with the Netlify CLI and we're considering a PR to change that which would require functions to be written under `.netlify` and so at that point we don't need to two sub-directories under `build`

2021-08-17 18:29 UTC, erezrokah commented
Hi @benmccann, are all SvelteKit's expected to be using the adapter?

I wonder if a more flexible approach would be to use a [Netlify Build Plugin](https://docs.netlify.com/configure-builds/build-plugins/create-plugins/)?
We do it with [Next.js](https://github.com/netlify/framework-info/blob/4b4881786daf22f61f66fa659fa6766b745be7df/src/frameworks/next.json#L22) and [Gatsby](https://github.com/netlify/framework-info/blob/4b4881786daf22f61f66fa659fa6766b745be7df/src/frameworks/gatsby.json#L23). That will allow you to have much better integration with the CLI and build process.

For example, the Next.js plugin writes to an internal functions directory:
https://github.com/netlify/netlify-plugin-nextjs/blob/92e099015ce4d95c2817d95d35d0b828ee463be4/index.js#L124.

2021-08-17 18:44 UTC, benmccann commented
The SvelteKit adapter is being updated to write to the internal functions directory. It would be nice if that directory were documented though. Right now we're having to rely on undocumented behavior and insights gleamed off how Gatsby and other tools work

I'm not that familiar with Netlify and the build plugins and whether they might be helpful, but I think it'd be hard to use SvelteKit without any adapter

2021-08-18 10:12 UTC, erezrokah commented
Hi @benmccann, after looking at https://github.com/sveltejs/kit/pull/2113, I believe we can move forward with this to unblock.

> It would be nice if that directory were documented though. Right now we're having to rely on undocumented behavior and insights gleamed off how Gatsby and other tools work

Very good point @benmccann, and we're planning to document those. We've been using them internally so we can iterate on the API.

> I'm not that familiar with Netlify and the build plugins and whether they might be helpful, but I think it'd be hard to use SvelteKit without any adapter

Thanks, that make sense. I think we can move forward with the PR.

2021-08-18 10:12 UTC, erezrokah approved these changes

2021-08-18 10:12 UTC, merged